// Frontends/Angular/src/app/login/login.component.ts
import { Component, OnInit, Input } from '@angular/core';
import {UserModel} from '../../models/userModel'

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  @Input() user: UserModel;
  
  constructor() {

  }

  SignIn() {

  }
  
  ngOnInit() {

  }

}


<form action="" class="form-content">
  <div class="row">

    <div class="col-sm-4 block-center">

      <div class="row">
        <div class="col-sm-12 mb-2">
          <img width="200" height="200" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
        </div>

      </div>

      <div class="form-group row">
        <div class="col-sm-12">
          <input type="text" placeholder="Login" name="login" [(ng-model)]="user.login" class="form-control" />
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-12">
          <input type="password" placeholder="Password" name="password" [(ng-model)]="user.password" class="form-control" />
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-12">
          <button type="button" (click)="SignIn()" class="btn btn-primary">Sign In</button>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <span>First time? <a href="/register">Sing Up </a></span>
        </div>
      </div>

    </div>

  </div>
</form>

// Frontends/react-app/src/pages/login.jsx
import React, { Component } from 'react';
import Logo from '../components/Logo/Logo.react';
import './login.css';
import Input from '../components/Input/Input.react'
import Button from '../components/Button/button.react'

class Login extends Component {
  state = { user: {} }

  constructor() {
    super();
    this.user = {}
  }

  setLogin = value => {

    this.user.login = value 
    this.setState({ user: this.user });
  }


  setPassword = value => {

    this.user.password = value 

    this.setState({ user: this.user });
  }

  render() {
    return (
      <form action="" class="form-content">
        <div class="row">

          <div class="col-sm-4 block-center">

            <div class="row">
              <Logo></Logo>

            </div>

            <div class="form-group row">
              <Input type="text" col="col-sm-12" placeholder="Login" setValue={this.setLogin} />
            </div>

            <div class="form-group row">
              <Input type="password" col="col-sm-12" placeholder="Password" setValue={this.setPassword} />
            </div>

            <div class="row mb-3">
              <Button col="col-sm-12" value="Sign In" user={this.state.user} />
            </div>
            <div class="row">
              <div class="col-sm-12">
                <span>First time? <a href="/register">Sing Up </a></span>
              </div>
            </div>

          </div>
        </div>
      </form >
    );
  }
}

export default Login;
